import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Category 1: Paan Corner (3 products)
        {
            name: 'Pan Parag',
            categoryId: 1,
            imageUrl: 'https://via.placeholder.com/200x200?text=Pan+Parag',
            quantity: '10 sachets',
            price: 10.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Rajnigandha',
            categoryId: 1,
            imageUrl: 'https://via.placeholder.com/200x200?text=Rajnigandha',
            quantity: '12 sachets',
            price: 12.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Vimal Pan Masala',
            categoryId: 1,
            imageUrl: 'https://via.placeholder.com/200x200?text=Vimal',
            quantity: '10 sachets',
            price: 15.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Pass Pass',
            categoryId: 1,
            imageUrl: 'https://via.placeholder.com/200x200?text=Pass+Pass',
            quantity: '8 sachets',
            price: 5.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 2: Dairy, Bread & Eggs (10 products)
        {
            name: 'Amul Taaza Milk',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Amul+Taaza',
            quantity: '500 ml',
            price: 28.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Amul Gold Milk',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Amul+Gold',
            quantity: '1 L',
            price: 68.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Mother Dairy Toned Milk',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Mother+Dairy',
            quantity: '500 ml',
            price: 26.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Amul Butter',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Amul+Butter',
            quantity: '100 g',
            price: 58.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Britannia Bread',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Britannia+Bread',
            quantity: '400 g',
            price: 40.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Modern White Bread',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Modern+Bread',
            quantity: '400 g',
            price: 35.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Farm Fresh Eggs',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Farm+Fresh+Eggs',
            quantity: '6 pcs',
            price: 42.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Brown Eggs',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Brown+Eggs',
            quantity: '12 pcs',
            price: 96.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Amul Cheese Slices',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Amul+Cheese',
            quantity: '200 g',
            price: 125.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Mother Dairy Paneer',
            categoryId: 2,
            imageUrl: 'https://via.placeholder.com/200x200?text=Paneer',
            quantity: '200 g',
            price: 85.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 3: Fruits & Vegetables (10 products)
        {
            name: 'Fresh Banana',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Banana',
            quantity: '1 dozen',
            price: 48.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Apple',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Apple',
            quantity: '4 pcs',
            price: 120.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Tomato',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Tomato',
            quantity: '500 g',
            price: 35.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Onion',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Onion',
            quantity: '1 kg',
            price: 45.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Potato',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Potato',
            quantity: '1 kg',
            price: 30.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Green Chilli',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Green+Chilli',
            quantity: '100 g',
            price: 20.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Lemon',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Lemon',
            quantity: '6 pcs',
            price: 25.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Coriander',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Coriander',
            quantity: '100 g',
            price: 15.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Capsicum',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Capsicum',
            quantity: '250 g',
            price: 55.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Cucumber',
            categoryId: 3,
            imageUrl: 'https://via.placeholder.com/200x200?text=Cucumber',
            quantity: '500 g',
            price: 28.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 4: Cold Drinks & Juices (8 products)
        {
            name: 'Coca Cola',
            categoryId: 4,
            imageUrl: 'https://via.placeholder.com/200x200?text=Coca+Cola',
            quantity: '750 ml',
            price: 40.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Pepsi',
            categoryId: 4,
            imageUrl: 'https://via.placeholder.com/200x200?text=Pepsi',
            quantity: '1 L',
            price: 45.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Sprite',
            categoryId: 4,
            imageUrl: 'https://via.placeholder.com/200x200?text=Sprite',
            quantity: '750 ml',
            price: 40.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Thums Up',
            categoryId: 4,
            imageUrl: 'https://via.placeholder.com/200x200?text=Thums+Up',
            quantity: '1.25 L',
            price: 55.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Tropicana Orange Juice',
            categoryId: 4,
            imageUrl: 'https://via.placeholder.com/200x200?text=Tropicana',
            quantity: '1 L',
            price: 120.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Real Juice Mixed Fruit',
            categoryId: 4,
            imageUrl: 'https://via.placeholder.com/200x200?text=Real+Juice',
            quantity: '1 L',
            price: 110.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Frooti Mango',
            categoryId: 4,
            imageUrl: 'https://via.placeholder.com/200x200?text=Frooti',
            quantity: '1 L',
            price: 65.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Maaza Mango',
            categoryId: 4,
            imageUrl: 'https://via.placeholder.com/200x200?text=Maaza',
            quantity: '1 L',
            price: 68.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 5: Snacks & Munchies (7 products)
        {
            name: 'Lays Classic',
            categoryId: 5,
            imageUrl: 'https://via.placeholder.com/200x200?text=Lays+Classic',
            quantity: '52 g',
            price: 20.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Kurkure Masala Munch',
            categoryId: 5,
            imageUrl: 'https://via.placeholder.com/200x200?text=Kurkure',
            quantity: '90 g',
            price: 30.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Haldirams Bhujia',
            categoryId: 5,
            imageUrl: 'https://via.placeholder.com/200x200?text=Haldirams+Bhujia',
            quantity: '200 g',
            price: 55.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Bingo Mad Angles',
            categoryId: 5,
            imageUrl: 'https://via.placeholder.com/200x200?text=Mad+Angles',
            quantity: '72 g',
            price: 25.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Uncle Chips',
            categoryId: 5,
            imageUrl: 'https://via.placeholder.com/200x200?text=Uncle+Chips',
            quantity: '90 g',
            price: 30.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Doritos Nacho Cheese',
            categoryId: 5,
            imageUrl: 'https://via.placeholder.com/200x200?text=Doritos',
            quantity: '150 g',
            price: 80.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Haldirams Aloo Bhujia',
            categoryId: 5,
            imageUrl: 'https://via.placeholder.com/200x200?text=Aloo+Bhujia',
            quantity: '400 g',
            price: 75.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 6: Breakfast & Instant Food (7 products)
        {
            name: 'Maggi 2-Minute Noodles',
            categoryId: 6,
            imageUrl: 'https://via.placeholder.com/200x200?text=Maggi',
            quantity: '280 g',
            price: 52.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Top Ramen Curry',
            categoryId: 6,
            imageUrl: 'https://via.placeholder.com/200x200?text=Top+Ramen',
            quantity: '280 g',
            price: 48.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Kelloggs Corn Flakes',
            categoryId: 6,
            imageUrl: 'https://via.placeholder.com/200x200?text=Corn+Flakes',
            quantity: '475 g',
            price: 185.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Saffola Oats',
            categoryId: 6,
            imageUrl: 'https://via.placeholder.com/200x200?text=Saffola+Oats',
            quantity: '1 kg',
            price: 195.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Quaker Oats',
            categoryId: 6,
            imageUrl: 'https://via.placeholder.com/200x200?text=Quaker+Oats',
            quantity: '500 g',
            price: 105.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'MTR Ready Mix Idli',
            categoryId: 6,
            imageUrl: 'https://via.placeholder.com/200x200?text=MTR+Idli',
            quantity: '500 g',
            price: 95.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Yippee Noodles',
            categoryId: 6,
            imageUrl: 'https://via.placeholder.com/200x200?text=Yippee',
            quantity: '240 g',
            price: 42.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 7: Sweet Tooth (6 products)
        {
            name: 'Cadbury Dairy Milk',
            categoryId: 7,
            imageUrl: 'https://via.placeholder.com/200x200?text=Dairy+Milk',
            quantity: '52 g',
            price: 40.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'KitKat',
            categoryId: 7,
            imageUrl: 'https://via.placeholder.com/200x200?text=KitKat',
            quantity: '37.3 g',
            price: 30.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: '5 Star',
            categoryId: 7,
            imageUrl: 'https://via.placeholder.com/200x200?text=5+Star',
            quantity: '40 g',
            price: 25.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Haldirams Soan Papdi',
            categoryId: 7,
            imageUrl: 'https://via.placeholder.com/200x200?text=Soan+Papdi',
            quantity: '250 g',
            price: 85.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Parle-G',
            categoryId: 7,
            imageUrl: 'https://via.placeholder.com/200x200?text=Parle+G',
            quantity: '250 g',
            price: 20.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Oreo Cookies',
            categoryId: 7,
            imageUrl: 'https://via.placeholder.com/200x200?text=Oreo',
            quantity: '120 g',
            price: 30.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 8: Atta, Rice & Dal (5 products)
        {
            name: 'Aashirvaad Atta',
            categoryId: 8,
            imageUrl: 'https://via.placeholder.com/200x200?text=Aashirvaad+Atta',
            quantity: '5 kg',
            price: 285.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'India Gate Basmati Rice',
            categoryId: 8,
            imageUrl: 'https://via.placeholder.com/200x200?text=Basmati+Rice',
            quantity: '1 kg',
            price: 185.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Toor Dal',
            categoryId: 8,
            imageUrl: 'https://via.placeholder.com/200x200?text=Toor+Dal',
            quantity: '500 g',
            price: 95.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Moong Dal',
            categoryId: 8,
            imageUrl: 'https://via.placeholder.com/200x200?text=Moong+Dal',
            quantity: '500 g',
            price: 88.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Rajma',
            categoryId: 8,
            imageUrl: 'https://via.placeholder.com/200x200?text=Rajma',
            quantity: '500 g',
            price: 105.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 9: Chicken, Meat & Fish (4 products)
        {
            name: 'Chicken Breast',
            categoryId: 9,
            imageUrl: 'https://via.placeholder.com/200x200?text=Chicken+Breast',
            quantity: '500 g',
            price: 225.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Mutton',
            categoryId: 9,
            imageUrl: 'https://via.placeholder.com/200x200?text=Mutton',
            quantity: '500 g',
            price: 485.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Fish Fillet',
            categoryId: 9,
            imageUrl: 'https://via.placeholder.com/200x200?text=Fish+Fillet',
            quantity: '500 g',
            price: 320.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Prawns',
            categoryId: 9,
            imageUrl: 'https://via.placeholder.com/200x200?text=Prawns',
            quantity: '250 g',
            price: 295.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 10: Masala, Oil & More (5 products)
        {
            name: 'Fortune Sunflower Oil',
            categoryId: 10,
            imageUrl: 'https://via.placeholder.com/200x200?text=Fortune+Oil',
            quantity: '1 L',
            price: 165.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'MDH Chana Masala',
            categoryId: 10,
            imageUrl: 'https://via.placeholder.com/200x200?text=MDH+Masala',
            quantity: '100 g',
            price: 68.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Everest Garam Masala',
            categoryId: 10,
            imageUrl: 'https://via.placeholder.com/200x200?text=Garam+Masala',
            quantity: '100 g',
            price: 72.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Tata Salt',
            categoryId: 10,
            imageUrl: 'https://via.placeholder.com/200x200?text=Tata+Salt',
            quantity: '1 kg',
            price: 22.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Red Chilli Powder',
            categoryId: 10,
            imageUrl: 'https://via.placeholder.com/200x200?text=Chilli+Powder',
            quantity: '100 g',
            price: 55.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 11: Sauces & Spreads (4 products)
        {
            name: 'Kissan Tomato Ketchup',
            categoryId: 11,
            imageUrl: 'https://via.placeholder.com/200x200?text=Kissan+Ketchup',
            quantity: '500 g',
            price: 95.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Maggi Tomato Sauce',
            categoryId: 11,
            imageUrl: 'https://via.placeholder.com/200x200?text=Maggi+Sauce',
            quantity: '500 g',
            price: 92.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Nutella',
            categoryId: 11,
            imageUrl: 'https://via.placeholder.com/200x200?text=Nutella',
            quantity: '350 g',
            price: 285.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Veeba Mayo',
            categoryId: 11,
            imageUrl: 'https://via.placeholder.com/200x200?text=Veeba+Mayo',
            quantity: '250 g',
            price: 125.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 12: Baby Care (3 products)
        {
            name: 'Pampers Diapers',
            categoryId: 12,
            imageUrl: 'https://via.placeholder.com/200x200?text=Pampers',
            quantity: '40 pcs',
            price: 425.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Johnson Baby Soap',
            categoryId: 12,
            imageUrl: 'https://via.placeholder.com/200x200?text=Johnson+Soap',
            quantity: '125 g',
            price: 68.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Cerelac',
            categoryId: 12,
            imageUrl: 'https://via.placeholder.com/200x200?text=Cerelac',
            quantity: '300 g',
            price: 245.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 13: Pharma & Wellness (3 products)
        {
            name: 'Dettol Soap',
            categoryId: 13,
            imageUrl: 'https://via.placeholder.com/200x200?text=Dettol+Soap',
            quantity: '125 g',
            price: 48.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Vicks Vaporub',
            categoryId: 13,
            imageUrl: 'https://via.placeholder.com/200x200?text=Vicks',
            quantity: '50 ml',
            price: 135.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Crocin',
            categoryId: 13,
            imageUrl: 'https://via.placeholder.com/200x200?text=Crocin',
            quantity: '15 tablets',
            price: 28.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 14: Cleaning Essentials (4 products)
        {
            name: 'Vim Bar',
            categoryId: 14,
            imageUrl: 'https://via.placeholder.com/200x200?text=Vim+Bar',
            quantity: '200 g',
            price: 32.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Harpic Toilet Cleaner',
            categoryId: 14,
            imageUrl: 'https://via.placeholder.com/200x200?text=Harpic',
            quantity: '500 ml',
            price: 95.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Surf Excel',
            categoryId: 14,
            imageUrl: 'https://via.placeholder.com/200x200?text=Surf+Excel',
            quantity: '500 g',
            price: 115.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Lizol Floor Cleaner',
            categoryId: 14,
            imageUrl: 'https://via.placeholder.com/200x200?text=Lizol',
            quantity: '500 ml',
            price: 88.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 15: Home & Office (3 products)
        {
            name: 'All Out Refill',
            categoryId: 15,
            imageUrl: 'https://via.placeholder.com/200x200?text=All+Out',
            quantity: '45 ml',
            price: 65.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Good Knight Refill',
            categoryId: 15,
            imageUrl: 'https://via.placeholder.com/200x200?text=Good+Knight',
            quantity: '45 ml',
            price: 62.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Classmate Notebook',
            categoryId: 15,
            imageUrl: 'https://via.placeholder.com/200x200?text=Notebook',
            quantity: '200 pages',
            price: 45.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 16: Personal Care (4 products)
        {
            name: 'Colgate Toothpaste',
            categoryId: 16,
            imageUrl: 'https://via.placeholder.com/200x200?text=Colgate',
            quantity: '200 g',
            price: 125.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Dove Soap',
            categoryId: 16,
            imageUrl: 'https://via.placeholder.com/200x200?text=Dove+Soap',
            quantity: '125 g',
            price: 78.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Head & Shoulders Shampoo',
            categoryId: 16,
            imageUrl: 'https://via.placeholder.com/200x200?text=Head+Shoulders',
            quantity: '340 ml',
            price: 245.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Gillette Razor',
            categoryId: 16,
            imageUrl: 'https://via.placeholder.com/200x200?text=Gillette',
            quantity: '1 pc',
            price: 185.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 17: Pet Care (3 products)
        {
            name: 'Pedigree Dog Food',
            categoryId: 17,
            imageUrl: 'https://via.placeholder.com/200x200?text=Pedigree',
            quantity: '1 kg',
            price: 385.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Whiskas Cat Food',
            categoryId: 17,
            imageUrl: 'https://via.placeholder.com/200x200?text=Whiskas',
            quantity: '1 kg',
            price: 365.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Pet Collar',
            categoryId: 17,
            imageUrl: 'https://via.placeholder.com/200x200?text=Pet+Collar',
            quantity: '1 pc',
            price: 195.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 18: Organic & Premium (3 products)
        {
            name: 'Organic Honey',
            categoryId: 18,
            imageUrl: 'https://via.placeholder.com/200x200?text=Organic+Honey',
            quantity: '500 g',
            price: 385.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Organic Quinoa',
            categoryId: 18,
            imageUrl: 'https://via.placeholder.com/200x200?text=Quinoa',
            quantity: '500 g',
            price: 425.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Organic Almonds',
            categoryId: 18,
            imageUrl: 'https://via.placeholder.com/200x200?text=Almonds',
            quantity: '250 g',
            price: 485.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 19: Ice Creams (3 products)
        {
            name: 'Amul Vanilla Ice Cream',
            categoryId: 19,
            imageUrl: 'https://via.placeholder.com/200x200?text=Amul+Ice+Cream',
            quantity: '1 L',
            price: 285.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Kwality Walls Cornetto',
            categoryId: 19,
            imageUrl: 'https://via.placeholder.com/200x200?text=Cornetto',
            quantity: '100 ml',
            price: 85.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Mother Dairy Ice Cream',
            categoryId: 19,
            imageUrl: 'https://via.placeholder.com/200x200?text=Mother+Dairy+Ice+Cream',
            quantity: '1 L',
            price: 265.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },

        // Category 20: Tea, Coffee & More (4 products)
        {
            name: 'Tata Tea Gold',
            categoryId: 20,
            imageUrl: 'https://via.placeholder.com/200x200?text=Tata+Tea',
            quantity: '500 g',
            price: 295.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Red Label Tea',
            categoryId: 20,
            imageUrl: 'https://via.placeholder.com/200x200?text=Red+Label',
            quantity: '500 g',
            price: 285.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Bru Coffee',
            categoryId: 20,
            imageUrl: 'https://via.placeholder.com/200x200?text=Bru+Coffee',
            quantity: '200 g',
            price: 325.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
        {
            name: 'Nescafe Classic',
            categoryId: 20,
            imageUrl: 'https://via.placeholder.com/200x200?text=Nescafe',
            quantity: '50 g',
            price: 185.0,
            deliveryTime: '8 mins',
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});